site_name: Carina
pages:
    - Overview: index.md
    - Getting started: getting_started.md
    - Project structure: project_structure.md
    - Configuration: configuration.md
    - Execution: execution.md
    - Advanced:
      - Web automation: advanced/web.md
      - Mobile automation: advanced/mobile.md
      - API automation: advanced/api.md
      - Drivers usage: advanced/drivers.md
      - Proxy: advanced/proxy.md
      - Database usage: advanced/databases.md
      - Security: advanced/security.md
      - Dataproviders: advanced/dataproviders.md
    - Cucumber: cucumber.md
    - Contribution: contribution.md
theme:
  name: 'material'
repo_url: https://github.com/qaprosoft/carina
repo_name: Github
